TOXIC_KEYWORDS = [
    "kill", 
    "murder", 
    "execute", 
    "assassinate", 
    "slaughter", 
    "liquidate", 
    "terminate", 
    "annihilate", 
    "eliminate",
    "hate",
    "terrorism",
    "violence",
    "beat", 
    "assault", 
    "hang", 
    "lynch", 
    "shoot", 
    "stab", 
    "burn", 
    "scald", 
    "choke", 
    "strangle", 
    "torture", 
    "mutilate", 
    "crush",
    "bullet", 
    "noose", 
    "gallows", 
    "rope", 
    "bomb", 
    "grenade", 
    "blade", 
    "machete", 
    "trigger", 
    "ied", 
    "acid",
    "riot", 
    "raid", 
    "smash", 
    "pillage", 
    "burn down", 
    "overrun", 
    "purge", 
    "eradicate", 
    "exterminate"
]

def toxicity_score(text: str) -> float:
    text_lower = text.lower()
    matches = sum(word in text_lower for word in TOXIC_KEYWORDS)
    return round(min(matches / len(TOXIC_KEYWORDS), 1.0), 2)
